### ISSUE TITLE
Bug: Currently not working

### ISSUE THREAD

**Issue by bdougie** [callmekatootie/carbonate#10]
When attempting to try this out in my own repo I found that imgur requires a callback authorization which wasn't documented in the readme. When trying to use your open issue, notice an error generating the image. 

https://github.com/callmekatootie/carbonate/issues/7#issuecomment-1020424775

## Question
Is this still working, would you like a contribution with a fix?

**Comment by callmekatootie** [comment]
Thank you for bringing this to my attention - will first check what's up and get back asap

**Comment by bdougie** [comment]
Curious if you could also share details needed for setting up the imgur side. Not sure what you used for the authorization callback, that would be helpful for debugging on my end.

**Comment by callmekatootie** [comment]
@bdougie Please check now. The api (Carbonara) used to generate the images changed their endpoint. This is now resolved and the images are generated once again - See https://github.com/callmekatootie/carbonate/issues/7#issuecomment-1021118930

As for the imgur api, this is how it is carried out - https://github.com/callmekatootie/carbonate/blob/master/index.js#L92-L115
