### ISSUE TITLE
Error when using Java code in issue: Unexpected token

### ISSUE THREAD

**Issue by McPringle** [callmekatootie/carbonate#11]
I like the idea of this action, so I added it to my repo but got the following error:

![2022-02-04 10_01_28-Merge remote-tracking branch 'origin_main' · komunumo_komunumo-server@452169c](https://user-images.githubusercontent.com/1254039/152501245-e4da4d71-d61e-4894-9ea5-7de2f8fc5de6.png)

Here is my issue with a simple Java code snippet I created for testing:
https://github.com/komunumo/komunumo-server/issues/247

As you can see, there is nothing special in the issue itself. I copied the action example from your README file and added no own configuration, so it will use all default settings. Here is my action:
https://github.com/komunumo/komunumo-server/blob/main/.github/workflows/carbonate.yml

It would be great if you can take a look at it why it does not work. It looks like it has a problem with the source code inside the issue, which is just plain Java.

**Comment by callmekatootie** [comment]
Testing your code here to debug it - I _think_ it could be because of Prettier... :

This issue is just a test for the carbonate action I just configured:

```java
default Optional<PageRecord> getPage(@NotNull final PageParent parent, @NotNull final String url) {
    return dsl().selectFrom(PAGE)
            .where(PAGE.PARENT.eq(parent).and(PAGE.PAGE_URL.eq(url)))
            .fetchOptional();
}
```

**Comment by callmekatootie** [comment]
Weird... no issue here... Would you be able to share the entire log?

**Comment by callmekatootie** [comment]
@McPringle Can you change this to `v1.0.2` instead of `v1` - https://github.com/komunumo/komunumo-server/blob/main/.github/workflows/carbonate.yml#L15 - and see if that resolves it?

**Comment by McPringle** [comment]
Thanks a lot, that worked! Which is a bit crazy, because according to the GitHub Actions documentation `@v1` is usually a shortcut with the meaning of "latest version of major version 1".

**Comment by callmekatootie** [comment]
yeah - I'll fix that in the README. Thank you for letting me know

**Comment by McPringle** [comment]
Thank you very much for your fast reply! 🥇

**Comment by callmekatootie** [comment]
That was quick! Thanks!
